export const Basic_Details = {
  Valve_Type: "",
  Recipe_Type: "NORMAL DATA",
  Coil_Voltage: "12V",
  Oil_Used: "",
  Oil_Temperature: "",
  Air_Test_Required: false,
  Pressure_Holding_Test_Required: false,
  No_of_Spools: 0,
  Pressure: "",
};

export const Tests = {
  Test_Sequence: [],
  Spool_Config: {
    "1_Right": 0,
    "2_Right": 0,
  },
  Tests: [
    {
      Name: "HPCO_TEST",
      Value: {
        Default_HPCO_Test: {
          Cycle_Time: 0,
          Maximum_System_Flow: 0,
          Maximum_System_Pressure: 0,
        },
        HPCO_Line: {
          Flow_Required: 0,
          FT: 0,
          Pressure_Drop: 0,
          PT: 0,
        },
      },
    },
    {
      Name: "MRV_Test",
      Value: {
        Pressure_Setting_MRV_Test: {
          Flow_Required: 0,
          FT: 0,
          Pressure_Drop: 0,
          PT: 0,
        },
        Cracked_Pressure_MRV_Test: {
          Flow_Required: 0,
          FT: 0,
          Pressure_Drop: 0,
          PT: 0,
        },
        Pressure_Setting_Verification_MRV_Test: {
          Flow_Required: 0,
          FT: 0,
          Pressure_Drop: 0,
          PT: 0,
        },
        Torquing_Value: 0,
        Default_MRV_Test: {
          Cycle_Time: 0,
          Maximum_System_Flow: 0,
          Maximum_System_Ptressure: 0,
        },
      },
    },
    {
      Name: "Leakage_Test_Data",
      Value: {
        Default_Leakage_Test: {
          Cycle_Time: 0,
          Maximum_System_Flow: 0,
          Maximum_System_Ptressure: 0,
        },
        Leakage_Test: {
          Spool_1: {
            Check_Valve_1: 0,
            Port_A1_T: 0,
            Port_B1_T: 0,
          },
          Spool_2: {
            Check_Valve_1: 0,
            Port_A1_T: 0,
            Port_B1_T: 0,
          },
          Spool_3: {
            Check_Valve_1: 0,
            Port_A1_T: 0,
            Port_B1_T: 0,
          },
          Spool_4: {
            Check_Valve_1: 0,
            Port_A1_T: 0,
            Port_B1_T: 0,
          },
          Spool_5: {
            Check_Valve_1: 0,
            Port_A1_T: 0,
            Port_B1_T: 0,
          },
          Spool_6: {
            Check_Valve_1: 0,
            Port_A1_T: 0,
            Port_B1_T: 0,
          },
          Spool_7: {
            Check_Valve_1: 0,
            Port_A1_T: 0,
            Port_B1_T: 0,
          },
          Spool_8: {
            Check_Valve_1: 0,
            Port_A1_T: 0,
            Port_B1_T: 0,
          },
          Spool_9: {
            Check_Valve_1: 0,
            Port_A1_T: 0,
            Port_B1_T: 0,
          },
          Spool_10: {
            Check_Valve_1: 0,
            Port_A1_T: 0,
            Port_B1_T: 0,
          },
        },
      },
    },
    {
      Name: "KickOut_Test",
      Value: {
        Default_KO_Test: {
          Cycle_Time: 0,
          Maximum_System_Flow: 0,
          Maximum_System_Pressure: 0,
        },
        HPCO_Line: {
          Flow_Required: 0,
          FT: 0,
          Pressure_Drop: 0,
          PT: 0,
        },
      },
    },
    {
      Name: "PRV_Test",
      Value: {
        Default_PRV_Test: {
          Cycle_Time: 0,
          Maximum_System_Flow: 0,
          Maximum_System_Pressure: 0,
        },
        HPCO_Line: {
          Flow_Required: 0,
          FT: 0,
          Pressure_Drop: 0,
          PT: 0,
        },

        PRV_A1_Test: false,
        PRV_B1_Test: false,
        PRV_A2_Test: false,
        PRV_B2_Test: false,
        PRV_A3_Test: false,
        PRV_B3_Test: false,
        PRV_A4_Test: false,
        PRV_A5_Test: false,
        PRV_B5_Test: false,
        PRV_A6_Test: false,
        PRV_B6_Test: false,
        PRV_A7_Test: false,
        PRV_B7_Test: false,
        PRV_A8_Test: false,
        PRV_B8_Test: false,
        PRV_A9_Test: false,
        PRV_B9_Test: false,
        PRV_A1_Test: false,
        PRV_B1_Test: false,
        PRV_Cr_ck_Test: {
          PRV_A1_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B1_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A2_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B2_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A3_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B3_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A4_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B4_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A5_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B5_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A6_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B6_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A7_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B7_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A8_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B8_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A9_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B9_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A10_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B10_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
        },
        PRV_Full_Test: {
          PRV_A1_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B1_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A2_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B2_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A3_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B3_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A4_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B4_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A5_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B5_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A6_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B6_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A7_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B7_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A8_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B8_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A9_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B9_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_A10_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
          PRV_B10_Test: {
            Pressure_Drop: 0,
            PT: 0,
            Flow_Drop: 0,
            FT: 0,
          },
        },
      },
    },
    {
      Name: "NAS",
      Value: {
        Test_Bench_Cleanliness_Required: 0,
        Ship_Away_Cleanliness_Required: 0,
        Offline_Cleanliness_Required: 0,
      },
    },
    {
      Name: "PD",
      Value: {
        Default_PD_Test: {
          Cycle_Time: 0,
          Maximum_System_Flow: 0,
          Maximum_System_Pressure: 0,
        },
        PD_Test: {
          Tank_Line_PD_Test: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          HPCO_Line_PD_Test: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          P_A: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          P_B: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          A_T: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          B_T: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          A1_B1_Line_PD_Test: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          A2_B2_Line_PD_Test: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          A3_B3_Line_PD_Test: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          A4_B4_Line_PD_Test: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          A5_B5_Line_PD_Test: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          A6_B6_Line_PD_Test: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          A7_B7_Line_PD_Test: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          A8_B8_Line_PD_Test: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          A9_B9_Line_PD_Test: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
          A10_B10_Line_PD_Test: {
            Flow_Required: 0,
            FT: 0,
            Pressure_Drop: 0,
            PT: 0,
          },
        },
      },
    },
  ],
};
